# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Bantool test

on:
  push:
    branches:
      - feature/*
      - master
      - hotfix/*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry run tox
    - name: Run tox via poetry
      run: |
        poetry run tox -p
